# Generated by Django 4.2.10 on 2024-02-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='blusa',
            new_name='Quantidade',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='bone',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='calca',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='saia',
        ),
        migrations.AddField(
            model_name='produtos',
            name='descrição',
            field=models.CharField(default='teste', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='nome',
            field=models.CharField(default='teste', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='preco',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
