# Generated by Django 4.2.10 on 2024-02-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0002_rename_blusa_produtos_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_de_nascimento', models.DateField()),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='descrição',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Quantidade',
            new_name='quantidade',
        ),
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='img_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
