# Generated by Django 4.2.10 on 2024-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2', '0004_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_de_nascimento',
            field=models.DateField(null=True),
        ),
    ]
